# Generated by Django 4.1 on 2022-08-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('row_id', models.IntegerField()),
                ('hadm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admittime', models.DateTimeField(blank=True, null=True)),
                ('dischtime', models.DateTimeField(blank=True, null=True)),
                ('deathtime', models.DateTimeField(blank=True, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=64, null=True)),
                ('admission_location', models.CharField(blank=True, max_length=64, null=True)),
                ('discharge_location', models.CharField(blank=True, max_length=64, null=True)),
                ('insurance', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=64, null=True)),
                ('religion', models.CharField(blank=True, max_length=64, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=64, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=64, null=True)),
                ('edregtime', models.CharField(blank=True, max_length=64, null=True)),
                ('edouttime', models.CharField(blank=True, max_length=64, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=256, null=True)),
                ('hospital_expire_flag', models.BooleanField(blank=True, null=True)),
                ('has_chartevents_data', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICUStays',
            fields=[
                ('row_id', models.IntegerField()),
                ('icustay_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dbsource', models.CharField(blank=True, max_length=10, null=True)),
                ('first_careunit', models.CharField(blank=True, max_length=10, null=True)),
                ('last_careunit', models.CharField(blank=True, max_length=10, null=True)),
                ('first_wardid', models.IntegerField(blank=True, null=True)),
                ('last_wardid', models.IntegerField(blank=True, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('los', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.admissions')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('row_id', models.IntegerField()),
                ('subject_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('dod', models.DateTimeField(blank=True, null=True)),
                ('dod_hosp', models.DateTimeField(blank=True, null=True)),
                ('dod_ssn', models.DateTimeField(blank=True, null=True)),
                ('expire_flag', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('row_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dbsource', models.CharField(blank=True, max_length=10, null=True)),
                ('eventtype', models.CharField(blank=True, max_length=10, null=True)),
                ('prev_careunit', models.CharField(blank=True, max_length=10, null=True)),
                ('curr_careunit', models.CharField(blank=True, max_length=10, null=True)),
                ('prev_wardid', models.SmallIntegerField(blank=True, null=True)),
                ('curr_wardid', models.SmallIntegerField(blank=True, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('los', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.admissions')),
                ('icustay_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mimic3.icustays')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('row_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transfertime', models.DateTimeField(blank=True, null=True)),
                ('prev_service', models.CharField(blank=True, max_length=20, null=True)),
                ('curr_service', models.CharField(blank=True, max_length=20, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.admissions')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('row_id', models.IntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=64, null=True)),
                ('drug', models.CharField(blank=True, max_length=64, null=True)),
                ('drug_name_poe', models.CharField(blank=True, max_length=64, null=True)),
                ('drug_name_generic', models.CharField(blank=True, max_length=64, null=True)),
                ('formulary_drug_cd', models.CharField(blank=True, max_length=64, null=True)),
                ('gsn', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('ndc', models.CharField(blank=True, max_length=64, null=True)),
                ('prod_strength', models.CharField(blank=True, max_length=64, null=True)),
                ('dose_val_rx', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('form_val_disp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('form_unit_disp', models.CharField(blank=True, max_length=10, null=True)),
                ('route', models.CharField(blank=True, max_length=10, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.admissions')),
                ('icustay_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mimic3.icustays')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients')),
            ],
        ),
        migrations.CreateModel(
            name='InputEvent_MV',
            fields=[
                ('row_id', models.IntegerField(primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(blank=True, max_length=20, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.admissions')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients')),
            ],
        ),
        migrations.AddField(
            model_name='icustays',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients'),
        ),
        migrations.AddField(
            model_name='admissions',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic3.patients'),
        ),
    ]
