# Generated by Django 4.1 on 2022-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimic3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='dose_unit',
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='dose_unit_rx',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dose_val_rx',
            field=models.CharField(blank=True, help_text='Not purely decimal, has different datatypes.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug_name_generic',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug_name_poe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='form_unit_disp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='form_val_disp',
            field=models.CharField(blank=True, help_text='Not purely decimal, has different datatypes.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='formulary_drug_cd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='gsn',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='ndc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prod_strength',
            field=models.CharField(blank=True, max_length=356, null=True),
        ),
    ]
