# Generated by Django 4.1 on 2022-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimic3', '0002_remove_prescriptions_dose_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='route',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
